# Generated by Django 4.2.7 on 2023-11-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignaturas',
            new_name='Asignatura',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
