# Generated by Django 4.2.7 on 2023-11-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_asignaturas_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='licencia',
            options={'verbose_name_plural': 'Licencias'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Profesores'},
        ),
    ]
