# Generated by Django 4.2.7 on 2023-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_asignatura_options_alter_licencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dias_ausente',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dias_presente',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='licencia',
            field=models.ManyToManyField(blank=True, null=True, to='home.licencia'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rut',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
