# Generated by Django 4.2.7 on 2023-11-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_teacher_dias_ausente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
