# Generated by Django 4.2.7 on 2023-11-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_teacher_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dias_ausente',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dias_presente',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
