# Generated by Django 4.2.7 on 2023-11-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_teacher_dias_ausente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='especialidad',
        ),
    ]
