# Generated by Django 4.2.7 on 2023-11-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_teacher_licencia_teacher_licencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='imagen',
            field=models.ImageField(upload_to='licencias/'),
        ),
    ]
