# Generated by Django 4.2.7 on 2023-12-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_licencia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dia_admi',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dias_ausente',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dias_presente',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
