# Generated by Django 4.2.7 on 2023-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_teacher_dia_admi_alter_teacher_dias_ausente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='asistencia_dates',
            field=models.ManyToManyField(blank=True, to='home.asistenciadate'),
        ),
    ]
