# Generated by Django 4.2.7 on 2023-12-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_asistenciadate_teacher_asistencia_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dia_licencia',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
